# Generated by Django 4.2.5 on 2023-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Recipes',
            fields=[
                ('recipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('recipe_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=300)),
                ('steps', models.CharField(max_length=300)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
