# Generated by Django 4.2.5 on 2023-11-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Data',
            fields=[
                ('recipe', models.IntegerField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=1000)),
                ('nutrition', models.CharField(max_length=50)),
                ('minutes', models.IntegerField()),
                ('ingredients', models.CharField(max_length=1000)),
                ('ethnicity', models.CharField(max_length=30)),
                ('type_of_food', models.CharField(max_length=30)),
                ('holiday', models.CharField(max_length=30)),
                ('dietary_restriction', models.CharField(max_length=30)),
                ('ingredients_bin', models.CharField(max_length=1000)),
                ('calories', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_steps', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('ingredients_html', models.CharField(max_length=1000)),
                ('steps_html', models.CharField(max_length=1000)),
                ('description_html', models.CharField(max_length=1000)),
                ('recipe_name_html', models.CharField(max_length=1000)),
                ('tag_bins', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='liked_recipes',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liked_recipes',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liked_recipes',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liked_recipes',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
