# Generated by Django 4.2.5 on 2023-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0004_alter_liked_recipes_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_recipes',
            name='tag_bins',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
