# Generated by Django 4.2.5 on 2023-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0005_liked_recipes_tag_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_recipes',
            name='ingredients_bin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
