# Generated by Django 4.2.5 on 2023-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0006_liked_recipes_ingredients_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_recipes',
            name='date_liked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
